name: Check URLs

on:
  workflow_dispatch: # Manually run workflow.
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.

jobs:
  check_urls:
    runs-on: ubuntu-latest
    # Do not run this job on forks, as it's not cool to query servers for nothing.
    if: ${{ github.repository == 'endoflife-date/endoflife.date' }}
    steps:
      - name: Checkout site
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup ruby
        uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1
        with:
          bundler-cache: true

      - name: Perform URLs check
        run: bundle exec jekyll build
        env:
          MUST_CHECK_URLS: true
